adminUser:
  password: vault:dconde-cjxd-4-ga1/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: dconde@cloudbees.com
  token: vault:dconde-cjxd-4-ga1/pipelineUser:token
  username: daveconde
prow:
  hmacToken: vault:dconde-cjxd-4-ga1/prow:hmacToken
